### ISSUE TITLE
TODO - Primeira implementação

### ISSUE THREAD

**Issue by henrimitte** [henrimitte/Gerador-e-Verificador-de-CPF#1]
- [ ] **Implementar função `verificaCpf(cpf: str)`**
  _Recebe um número de C.P.F. com 11 dígitos, sem os pontos e retorna um boolean._
  - [ ] Verificar se todos os caracteres são números
  - [ ] Verificar se o número contém 11 dígitos
  - [ ] Armazenar os dígitos verificadores na variável `checkDigit = tuple()` 
  - [ ] Calcular os dígitos verificadores e armazenar na variável `afterCheckDigit = list()`
  - [ ] Comparar as variáveis `checkDigit == afterCheckDigit`
  - [ ] Se ambas forem iguais, retorna `True`, caso contrário, retorna `False`
